#!bin/bash
##shell script to print numbers 1 to 100
#
#i=1
#while [ $i -le 100 ]
#do
#    echo $i
#    i=$(($i+1))
#done
#
#i=1
#while [ $i -le 38 ]
#do
#  echo $i
#  i=$(($i+1))
#done


i=1
while [ $1 -le 5550]
do
  echo $i
  i=$(($i+1))
done